name: On Push to Main, Version and Tag For Release
on:
  push:
    branches:
    - main

permissions:
  packages: write
  contents: write

jobs:
  quality:
    uses: harmony-labs/workflows-rust/.github/workflows/quality.yaml@v1.1.0
    with:
      cargo_incremental: true


  # This uses commit logs and tags from git to determine the next version number and create a tag for the release
  # Some commits such are chore: will not trigger a version bump and tag! This is by design.
  version-and-tag:
    name: Version and Tag
    needs: quality
    uses: harmony-labs/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.5.0
    secrets: inherit
    with:
      useDeployKey: true
      rust: true
